name: Python Greetings CI/CD

on:
  push:
    branches:
      - main

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - uses: ./.github/actions/setup-python-greetings

  deploy-to-dev:
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - uses: ./.github/actions/deploy-python-greetings
        with:
          environment_name: dev
          port: 7001

  tests-on-dev:
    runs-on: self-hosted
    needs: deploy-to-dev
    steps:
      - uses: ./.github/actions/test-greetings
        with:
          environment_name: dev

  deploy-to-stg:
    runs-on: self-hosted
    needs: tests-on-dev
    steps:
      - uses: ./.github/actions/deploy-python-greetings
        with:
          environment_name: stg
          port: 7002

  tests-on-stg:
    runs-on: self-hosted
    needs: deploy-to-stg
    steps:
      - uses: ./.github/actions/test-greetings
        with:
          environment_name: stg

  deploy-to-preprod:
    runs-on: self-hosted
    needs: tests-on-stg
    steps:
      - uses: ./.github/actions/deploy-python-greetings
        with:
          environment_name: preprod
          port: 7003

  tests-on-preprod:
    runs-on: self-hosted
    needs: deploy-to-preprod
    steps:
      - uses: ./.github/actions/test-greetings
        with:
          environment_name: preprod

  deploy-to-prod:
    runs-on: self-hosted
    needs: tests-on-preprod
    steps:
      - uses: ./.github/actions/deploy-python-greetings
        with:
          environment_name: prod
          port: 7004

  tests-on-prod:
    runs-on: self-hosted
    needs: deploy-to-prod
    steps:
      - uses: ./.github/actions/test-greetings
        with:
          environment_name: prod